# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 798d55b50a175a460256b4205e46b9fddcc860ec1314e82aaf6b3211e95c461bddfda8760811d038fea1b7141d45beed19855f8500fb1e815f93b612da0d4a0e

test:
  secret_key_base: f60a243479d8520d7c817779ff196b6058f393278cccf518528c57368f7973af978aaadb89b0d22f45e991f666b28874b4a37792e950ee9a9d1067bab36978b9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
